### ISSUE TITLE
using se_resnext

### ISSUE THREAD

**Issue by JosephPai** [lulujianjie/person-reid-tiny-baseline#15]
Hi JackLu,

I really like your code, it's clean yet effective.
I want to adapt se_resnext from [official code](https://github.com/michuanhaohao/reid-strong-baseline/blob/master/modeling/backbones/senet.py).
I copy the `senet.py` file to `model/bacbones`, then I add the following code in `model/make_model.py` line 46:

```
        elif model_name == 'se_resnext50':
            self.in_planes = 2048
            self.base = SENet(block=SEResNeXtBottleneck,
                              layers=[3, 4, 6, 3],
                              groups=32,
                              reduction=16,
                              dropout_p=None,
                              inplanes=64,
                              input_3x3=False,
                              downsample_kernel_size=1,
                              downsample_padding=0,
                              last_stride=last_stride)
```

I also prepared the ImageNet pre-traind weights and configs.
Then `python train.py`
The code runs well, but the mAP is not increasing even after many epochs, it stuck in about 0.2%.
I think do not modify other codes, do you have any idea about it?
Thanks a lot!!!

**Comment by lulujianjie** [comment]
It is probably caused by the wrong model code. I have tried SEnet. It works in reid-task.
