### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by murdockhou** [lulujianjie/person-reid-tiny-baseline#4]
你好，谢谢你的实现，问一个比较愚蠢的问题，`utils/metrics.py`里，函数`eval_func`里代码`matches = (g_pids[indices] == q_pids[:, np.newaxis]).astype(np.int32)`是什么意思？`matches`没一行表示的是什么意思？

还有就是，如果re-id网络在实际运用的时候，是不是只需要计算下待查找的box的特征，然后和检索库中计算所有待检索box的特征相比较，把距离（欧式距离或者余弦距离）最近的前N（1 or 5 or 10)个待检索的box取出来就可以了？

小白一枚，刚接触person-reid，望不吝赐教，感谢

**Comment by lulujianjie** [comment]
A1:As you can see, `indices = np.argsort(distmat, axis=1)` return the indices of nearest images.
So we need to determine whether the results of these nearest images match the ground truth. This is the meaning of `matches = (g_pids[indices] == q_pids[:, np.newaxis]).astype(np.int32)`
A2:Yes!
