### ISSUE TITLE
KeyError: 'base.conv1.weight'

### ISSUE THREAD

**Issue by 58570305** [lulujianjie/person-reid-tiny-baseline#6]
```
How to solve the following problems?
KeyError: 'base.conv1.weight'
$ python train.py 
2019-10-14 11:04:01,139 person-reid-tiny-baseline INFO: Running with config:
person-reid-tiny-baseline
=> Market1501 loaded
Dataset statistics:
  ----------------------------------------
  subset   | # ids | # images | # cameras
  ----------------------------------------
  train    |   751 |    12936 |         6
  query    |   750 |     3368 |         6
  gallery  |   751 |    15913 |         6
  ----------------------------------------
using triplet sampler
Traceback (most recent call last):
  File "train.py", line 23, in <module>
    model = make_model(Cfg, num_class=num_classes)
  File "/home/dd/wind/0ReID/person-reid-tiny-baseline/model/make_model.py", line 98, in make_model
    model = Backbone(num_class, Cfg)
  File "/home/dd/wind/0ReID/person-reid-tiny-baseline/model/make_model.py", line 48, in __init__
    self.base.load_param(model_path)
  File "/home/dd/wind/0ReID/person-reid-tiny-baseline/model/backbones/resnet.py", line 133, in load_param
    self.state_dict()[i].copy_(param_dict[i])
KeyError: 'base.conv1.weight'
```

**Comment by lulujianjie** [comment]
It may be caused by pytorch multi-GPU saving model. Try to:
1. modify 'self.state_dict()[i].copy_(param_dict[i])' to `self.state_dict()[i[7:]].copy_(param_dict[i])`
or 
2. modify 'self.state_dict()[i].copy_(param_dict[i])' to `self.state_dict()[i].copy_(param_dict['module.'+i])`
If you cannot still solve it, please feel free to let me know.

**Comment by 58570305** [comment]
Thank you for your reply!

```
情况1:
            if 'fc' in i:
                continue
            self.state_dict()[i[7:]].copy_(param_dict[i])
错误提示:
    self.state_dict()[i[7:]].copy_(param_dict[i])
KeyError: 'nv1.weight'
---------------------------------------------
情况2:
            if 'fc' in i:
                continue
            self.state_dict()[i].copy_(param_dict['module.' + i])
错误提示:
    self.state_dict()[i].copy_(param_dict['module.' + i])
KeyError: 'base.conv1.weight'


我这样修改后就解决了
            if 'fc' or 'base.conv1.weight' in i:
                 continue
             self.state_dict()[i].copy_(param_dict[i])

**Comment by lulujianjie** [comment]
You can not do that since it will ignore conv1's weight. I will test it and provide a new model's weights.

**Comment by 58570305** [comment]
Thank you! wait for your model.

**Comment by roywithfiringblade** [comment]
@58570305 i think maybe you didn't load the pre-trained model and backbone correct. you can check the official code for some inspiration.

**Comment by HWNHJJ** [comment]
could you solve this problem  and send me the model's weight?I meet the same problem.

**Comment by mojiayuan** [comment]
> You can not do that since it will ignore conv1's weight. I will test it and provide a new model's we
你好，请问新的模型更新了吗，还是会遇到这个问题KeyError: 'base.conv1.weight'

**Comment by mojiayuan** [comment]
> el = Backbone(num_class, Cfg)
>   File "/home/dd/wind/0ReID/person-reid-tiny-baseline/model/make_model.py", line 48, in __init__
>     self.base.load_param(model_path)
>   File "/home/dd/wind/0ReID/person-reid-tiny-baseline/model/backbones/resnet.py", line 133, in load_param
>     self.state_dict()[i].copy_(param_dict[i])
> KeyError: 'base.conv1.weight'
请问你解决这个问题了吗
