### ISSUE TITLE
ValueError: too many values to unpack (expected 3)and KeyError: 'nv1.weight'

### ISSUE THREAD

**Issue by TheLeopardsH** [lulujianjie/person-reid-tiny-baseline#9]
In training,after 5 epochs I recieved this error  "ValueError: too many values to unpack (expected 3)" and I am not able to figure out after a lot of debugging.Screenshot is attached below

After not able to figure out I tried to test  your pretained model,this error comes "  KeyError: 'nv1.weight'  ".Screenshot is attached below.

Can you tell whats wrong in errors
python train.py
![Error](https://user-images.githubusercontent.com/48291620/70386930-ba67c700-19c0-11ea-8713-e3be4c987aa8.PNG)
python test.py
![error2](https://user-images.githubusercontent.com/48291620/70386932-bcca2100-19c0-11ea-908b-7ba304eac803.PNG)

(url)

**Comment by TheLeopardsH** [comment]
I fixed the 2nd error " KeyError: 'nv1.weight' "  but first error "ValueError: too many values to unpack (expected 3)" ,I am still not able to solve it.

**Comment by lulujianjie** [comment]
Change line 83 in do_train of processor.py as :
```python
for iter, (img, vid, camid, _ ) in enumerate(val_loader)
```

**Comment by gbrvalerio** [comment]
how did you manage to fix `nv1.weight` error, @TheLeopardsH ?
